[[plugin.deps]]
use = "ndtoan96/ouch"
rev = "cfb9140"
hash = "b5067143415bd2d46c0dfa57319ddcef"

[[flavor.deps]]
use = "yazi-rs/flavors:catppuccin-latte"
rev = "ffe6e3a"
hash = "525675a9180ed23a097b07399627294a"

[[flavor.deps]]
use = "yazi-rs/flavors:catppuccin-frappe"
rev = "ffe6e3a"
hash = "6f261f00e5235001b8d6bcd7464d3077"

[[flavor.deps]]
use = "yazi-rs/flavors:catppuccin-macchiato"
rev = "ffe6e3a"
hash = "b069dba45e199684b16fa12d385642ed"

[[flavor.deps]]
use = "yazi-rs/flavors:catppuccin-mocha"
rev = "ffe6e3a"
hash = "b951d27afe197d154f6da9683b46c5f8"
